from  tkinter import *
def RegistreerMenu():
    window = Tk()
    window.title("Registreren")
    label = Label(window, text="Fiets Registreren", fg="white", bg="blue")
    label.config(height="1", width="50")
    label.pack()
    naam = Label(window, text="Naam:", fg="white", bg="blue")
    naam.config(height="1", width="5")
    naam.place(x="73", y="65")
    e = Entry(window)
    e.place(x="114", y="66")
    buttongadoor = Button(window, text="Registreer Gegevens", fg="white", bg="blue")
    buttongadoor.config(height="1", width="15")
    buttongadoor.place(x="185", y="174")
    buttongaterug = Button(window, text="Ga terug", fg="white", bg="red")
    buttongaterug.config(height="1", width="15")
    buttongaterug.place(x="0",y="174")
    window.configure(background="yellow")
    window.maxsize(300,200)
    window.minsize(300,200)
    window.mainloop()

RegistreerMenu()
